version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/y-yagi/gtodo
    steps:
      - checkout

      - run:
          name: Run lint
          command: |
            go get -u golang.org/x/lint/golint
            golint -set_exit_status ./...
      - Run:
          name: Run go mod
          command: |
            go mod download
            go mod vendor

      - run:
          name: Run megacheck
          command: |
            go get -u honnef.co/go/tools/cmd/megacheck
            GO111MODULE=off megacheck ./...

  modules-update:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/y-yagi/gtodo

    steps:
      - checkout
      - run:
          name: Run ci-modules-update
          command: |
            GO111MODULE=off go get -u github.com/y-yagi/ci-modules-update
            ci-modules-update -u y-yagi -r y-yagi/gtodo

workflows:
  version: 2
  build:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 22 * * 1"
          filters:
            branches:
              only: master
    jobs:
      - modules-update
