version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/y-yagi/gtodo
    steps:
      - checkout

      - run:
          name: Run lint
          command: |
            GO111MODULE=off go get -u golang.org/x/lint/golint
            golint -set_exit_status ./...
      - Run:
          name: Run go mod
          command: |
            go mod download
            go mod vendor

      - run:
          name: Run staticcheck
          command: |
            GO111MODULE=off go get -u honnef.co/go/tools/cmd/staticcheck
            GO111MODULE=off staticcheck ./...

workflows:
  version: 2
  build:
    jobs:
      - build
